export { default as Header } from './Header/Header'
export { default as AuthModal } from './AuthModal/AuthModal'
export { default as News } from './News/News'
export { default as NewsItem } from './NewsItem/NewsItem'
export { default as AddNews } from './AddNews/AddNews'
